# print('hello world')
# my_name = input("introduction: ")
# print(type(my_name))
# print(len(my_name))
# print(my_name. upper())
# print(my_name. capitalize())
# print(my_name. lower())
#
my_name = 'intro'
print(my_name[0])
print(my_name[1])
print(my_name[-1])
print(my_name[-2])
print(my_name[-3])
print(my_name[-4])
print(my_name[-5])
print(my_name[0:-1])
print(my_name[0:len(my_name) -1])
print(my_name[:])

print("Welcome", my_name, "to DIS11")
